### ISSUE TITLE
AMPI ROMIO build is broken

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#3727]
Presumably broken by PR #3721 commit `1f6389a185b4709b57df471bec940a0664b90ef0`, `2b9c51b9702a1e6e47a1fe1f1273160dd28b23aa`, or `7d255608679f0f08045f08fb17590e7580afde27`.

Build command: `./build  AMPI  multicore-darwin-x86_64  --with-production`

Error:
```
...
  CC       adio/common/p2p_aggregation.lo
  CC       adio/common/onesided_aggregation.lo
  CC       adio/common/utils.lo
  CCLD     libromio.la
[ 95%] No install step for 'romio'
[ 96%] Completed 'romio'
[ 96%] Built target romio
[ 96%] Building CXX object src/libs/ck-libs/ampi/CMakeFiles/moduleampi.dir/ampi.C.o

In file included from ~/charm/src/libs/ck-libs/ampi/ampi.C:8:
In file included from ~/charm/src/libs/ck-libs/ampi/ampiimpl.h:21:
In file included from ~/charm/src/libs/ck-libs/ampi/ampi.h:1394:
In file included from ~/charm/src/libs/ck-libs/ampi/ampi_functions.h:571:
~/charm/multicore-darwin-x86_64/include/mpio_functions.h:67:23: error: unknown type name 'MPIO_Request'; did you mean 'MPI_Request'?
                      MPIO_Request *request)
                      ^~~~~~~~~~~~
                      MPI_Request
~/charm/src/libs/ck-libs/ampi/ampi.h:1392:26: note: expanded from macro 'AMPI_CUSTOM_FUNC'
#define AMPI_CUSTOM_FUNC AMPI_CUSTOM_API_DEF
                         ^
~/charm/src/libs/ck-libs/ampi/ampi.h:36:50: note: expanded from macro 'AMPI_CUSTOM_API_DEF'
  extern return_type AMPI_FUNCPTR(function_name)(__VA_ARGS__);
                                                 ^
~/charm/src/libs/ck-libs/ampi/ampi.h:348:13: note: 'MPI_Request' declared here
typedef int MPI_Request;
            ^
```

**Comment by evan-charmworks** [comment]
I was unable to reproduce this with an up-to-date main branch, clean repository (`git clean -xdf`), and the exact build command posted (no parallelism).

This log output has the symptoms of the bug I referred to in b885ca568adb577c24f830b0fe43162508cb4664.

**Comment by evan-charmworks** [comment]
Just to be sure, I ran `brew unlink gcc` to disable gfortran / Fortran support and a build in that environment completed successfully too.

**Comment by stwhite91** [comment]
Rebuilding from a clean repository I'm unable to reproduce this
