### PR TITLE
CI: Use UCX v1.9.0

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Review by matthiasdiener — APPROVED** [review]

**Comment by evan-charmworks** [comment]
UCX v1.9.0 CI failed with this and I don't know what changed.

```
In file included from /home/runner/work/charm/charm/src/arch/ucx/machine.C:30:0:
/home/runner/work/charm/charm/ucx-linux-x86_64-ompipmix/bin/../include/runtime-pmix.C:9:10: fatal error: pmix.h: No such file or directory
 #include <pmix.h>
          ^~~~~~~~
```

Multicore Darwin Tracing failed due to #2763.

**Comment by matthiasdiener** [comment]
> UCX v1.9.0 CI failed with this and I don't know what changed.
> 
> ```
> In file included from /home/runner/work/charm/charm/src/arch/ucx/machine.C:30:0:
> /home/runner/work/charm/charm/ucx-linux-x86_64-ompipmix/bin/../include/runtime-pmix.C:9:10: fatal error: pmix.h: No such file or directory
>  #include <pmix.h>
>           ^~~~~~~~
> ```

Might be related to the OpenMPI version change.

**Comment by matthiasdiener** [comment]
> > UCX v1.9.0 CI failed with this and I don't know what changed.
> > ```
> > In file included from /home/runner/work/charm/charm/src/arch/ucx/machine.C:30:0:
> > /home/runner/work/charm/charm/ucx-linux-x86_64-ompipmix/bin/../include/runtime-pmix.C:9:10: fatal error: pmix.h: No such file or directory
> >  #include <pmix.h>
> >           ^~~~~~~~
> > ```
> 
> Might be related to the OpenMPI version change.

Seems that OpenMPI will remove the option to install libpmix libs/headers: https://github.com/open-mpi/ompi/issues/6228

**Comment by evan-charmworks** [comment]
I am able to reproduce the PMIX issue locally.

This symbol issue leads me to think PMIX should be built after Open MPI.

```
$ grep -r pointer_array_t
Binary file openmpi/mca_rmaps_rank_file.so matches
Binary file openmpi/libompi_dbg_msgq.so matches
Binary file openmpi/mca_ess_hnp.so matches
Binary file openmpi/mca_btl_openib.so matches
Binary file openmpi/mca_errmgr_default_orted.so matches
Binary file openmpi/mca_ras_slurm.so matches
Binary file openmpi/mca_rmaps_resilient.so matches
Binary file openmpi/mca_pmix_pmix3x.so matches
Binary file libopen-pal.so.40.20.5 matches
Binary file libpmi.so.1.0.1 matches
Binary file libpmi2.so.1.0.0 matches
Binary file pmix/mca_bfrops_v20.so matches
Binary file pmix/mca_bfrops_v12.so matches
Binary file pmix/mca_bfrops_v21.so matches
Binary file pmix/mca_bfrops_v3.so matches
Binary file libmpi.so.40.20.5 matches
Binary file libopen-rte.so.40.20.5 matches
Binary file libpmix.so.2.2.25 matches
$ nm -D libpmix.so.2.2.25 | grep pointer_array_t
0000000000316fe0 D pmix_pointer_array_t_class
0000000000014480 T pmix_pointer_array_test_and_set_item
$ nm -D pmix/mca_bfrops_v21.so | grep pointer_array_t
                 U OPAL_MCA_PMIX3X_pmix_pointer_array_t_class
$ grep -r OPAL_MCA_PMIX3X_pmix_pointer_array_t_class
Binary file openmpi/mca_pmix_pmix3x.so matches
Binary file pmix/mca_bfrops_v20.so matches
Binary file pmix/mca_bfrops_v12.so matches
Binary file pmix/mca_bfrops_v21.so matches
Binary file pmix/mca_bfrops_v3.so matches
```

**Comment by evan-charmworks** [comment]
Now it does this.

```
[fv-az148:15083] *** Process received signal ***
[fv-az148:15083] Signal: Segmentation fault (11)
[fv-az148:15083] Signal code: Address not mapped (1)
[fv-az148:15083] Failing at address: 0x20
[fv-az148:15083] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7ffff7237fd0]
[fv-az148:15083] [ 1] /usr/local/lib/pmix/mca_ptl_tcp.so(+0x3beb)[0x7ffff284cbeb]
[fv-az148:15083] [ 2] /usr/local/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_pmix_mca_base_framework_components_open+0x9f)[0x7ffff3f6369f]
[fv-az148:15083] [ 3] /usr/local/lib/openmpi/mca_pmix_pmix3x.so(+0x11b46e)[0x7ffff3f8446e]
[fv-az148:15083] [ 4] /usr/local/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_pmix_mca_base_framework_open+0x81)[0x7ffff3f64111]
[fv-az148:15083] [ 5] /usr/local/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_pmix_rte_init+0x8e0)[0x7ffff3f33c80]
[fv-az148:15083] [ 6] /usr/local/lib/openmpi/mca_pmix_pmix3x.so(OPAL_MCA_PMIX3X_PMIx_server_init+0x273)[0x7ffff3f15313]
[fv-az148:15083] [ 7] /usr/local/lib/openmpi/mca_pmix_pmix3x.so(pmix3x_server_init+0x2db)[0x7ffff3ea152b]
[fv-az148:15083] [ 8] /usr/local/lib/libopen-rte.so.40(pmix_server_init+0x3c7)[0x7ffff7b5f0e7]
[fv-az148:15083] [ 9] /usr/local/lib/openmpi/mca_ess_hnp.so(+0x445c)[0x7ffff53f045c]
[fv-az148:15083] [10] /usr/local/lib/libopen-rte.so.40(orte_init+0x291)[0x7ffff7ba7391]
[fv-az148:15083] [11] /usr/local/lib/libopen-rte.so.40(orte_submit_init+0x764)[0x7ffff7bab924]
[fv-az148:15083] [12] mpirun(+0xf0f)[0x555555554f0f]
[fv-az148:15083] [13] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7ffff721ab97]
[fv-az148:15083] [14] mpirun(+0xd6a)[0x555555554d6a]
[fv-az148:15083] *** End of error message ***
```

**Review by matthiasdiener — APPROVED** [review]
I think this is ok for now, but longer term we should fix the issues with the openmpi installation. The `--enable-install-libpmix` parameter is apparently going away.

**Review by minitu — APPROVED** [review]
