### ISSUE TITLE
CkMulticast support for Group sections breaks in STL headers

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1262]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1262*

---
The use of std::placeholders and std::bind fails to compile with the STL headers that are used on autobuild's netlrts-linux-x86_64-tcp, mpi-win64, and gni-crayxc builds. XLC and other tests were not run, but might suffer the same failures.

ckmulticast.C(615): error: namespace "std" has no member "placeholders"
ckmulticast.C(616): error: namespace "std" has no member "bind"

https://charm.cs.illinois.edu/autobuild/cur/gni-crayxc.txt

**Comment by stwhite91** [comment]
*Original date: 2016-10-17 13:39:06*

---
Fix with high prioriity or else revert the offending commit until it can be fixed: ~~https://charm.cs.illinois.edu/gerrit/#/c/1287/~~ https://github.com/UIUC-PPL/charm/commit/bb8df90f64be6b9823a052ff401d51fdaf6ab230

**Comment by stwhite91** [comment]
*Original date: 2016-10-18 00:57:23*

---
Workaround is here: ~~https://charm.cs.illinois.edu/gerrit/#/c/1923/~~ https://github.com/UIUC-PPL/charm/commit/defdd160818a16e3dc758a7d7650bc7adc54d26e

We would like to know what compiler versions are needed to support this particular use of std::bind, to see if we can just bump our compiler requirements
