### PR TITLE
cmake: fix charm4py build

### PR DESCRIPTION
**Pull request by matthiasdiener**
Error introduced in #2531.

Note that even after this change, charm4py still does not build, both with the cmake and old build:

```
$ ./buildold charm4py netlrts-darwin-x86_64 -j8 --suffix=old
[...]
cd ../lib ; ../bin/charmc   -standalone -whole-archive -c++stl -shared -o libcharm.so libck.a libconv-core.a libconv-util.a libmemory-default.a libconv-machine.a libthreads-default.a libconv-partition.a libtmgr.a libhwloc_embedded.a libldb-rand.a libconv-ldb.a libmoduleTreeLB.a
duplicate symbol '_registerTreeLevel()' in:
    libck.a(TreeLB.o)
    libmoduleTreeLB.a(TreeLB.o)
duplicate symbol 'CkIndex_TreeLB::_callmarshall_reportLbTime_marshall8(char*, void*)' in:
    libck.a(TreeLB.o)
    libmoduleTreeLB.a(TreeLB.o)
[...]
```

### CODE REVIEW

**Comment by rbuch** [comment]
This branch built successfully for me using `./build charm4py netlrts-linux-x86_64` on my machine.

**Comment by matthiasdiener** [comment]
> This branch built successfully for me using `./build charm4py netlrts-linux-x86_64` on my machine.

Yes, since I removed moduleTreeLB from the link command as a test. Is this fix is correct? Also,  I have not ported this fix to the old build system, which still fails to build charm4py.

**Comment by rbuch** [comment]
> > This branch built successfully for me using `./build charm4py netlrts-linux-x86_64` on my machine.
> 
> Yes, since I removed moduleTreeLB from the link command as a test ([de5ff34](https://github.com/UIUC-PPL/charm/commit/de5ff341505d4e1aed0724a7c5d73a3ca8f6af33)). Is this fix is correct? Also, I have not ported this fix to the old build system, which still fails to build charm4py.
> 
> Edit:
> If this fix is correct, why is there still a `libmoduleTreeLB` if TreeLB is already in `libck`? Wouldn't that always cause linking issues?

I'm not sure, I don't think there's any reason for it to be in `libck` other than maybe the charm4py LB registration code.

**Comment by matthiasdiener** [comment]
Removing TreeLB from libck also leads to linking errors:

```
../../../bin/charmc  -language charm++ -o hello hello.o
Undefined symbols for architecture x86_64:
  "_registerTreeLevel()", referenced from:
      _initCharm(int, char**) in libck.a(init.C.o)
  "TreeLB::configure(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer>&)", referenced from:
      LBManager::configureTreeLB(nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer>&) in libck.a(LBManager.C.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by matthiasdiener** [comment]
Ready for review.
